### ISSUE TITLE
Week 1: Project Prerequisites

### ISSUE THREAD

**Issue by connor-cozens** [connor-cozens/covid19-school-dashboard#19]
### Install Local Software
- RStudio
- Github

### Learning R
[DataCamp Tutorial](https://www.datacamp.com/courses/free-introduction-to-r)
[w3 Schools](https://www.w3schools.com/r/)

### Learning Git
[Atlassian Tutorial](https://www.atlassian.com/git/tutorials)
[Video Tutorial](https://www.youtube.com/watch?v=8JJ101D3knE)

### TODOs
- [x] Invite to Repository
- [x] Install all local software listed above
- [x] Complete Git tutorial(s)
- [x] Complete R tutorial(s)
